<div class="security">
    <div class="l_title">CHÍNH SÁCH BẢO MẬT THÔNG TIN</div>
    <div class="box_nd">
        <div class="l_main">
            <i > <p class="main_item1">
            Là website hoạt động ở lĩnh vực dịch vụ, timviec365.com luôn nỗ lực trong việc mang lại sự trải nghiệm tối ưu nhất cho người dùng. Đó cũng chính là lý do, chúng tôi luôn chú trọng và tôn trọng thông tin cá nhân của người dùng. Không dừng lại ở lĩnh vực tìm việc,  timviec365.com còn cung cấp đến khách người nhiều phần mềm quản trị nhân lực, trong đó tiêu biểu nhất là PC365. Đây là ứng dụng hỗ trợ đắc lực cho các doanh nghiệp đa dạng quy mô quản lý công cán phục vụ tính lương, triển khai kế hoạch công việc thông qua quá trình điểm danh nhận diện khuôn mặt và QR chính xác, nhanh chóng. Trước khi tham gia vào các cuộc giao dịch trên hệ thống timviec365.com nói chung và trở thành khách hàng thân thiết của PC365 hãy chắc chắn rằng, tất cả các bạn tìm hiểu, nắm bắt các thông tin về chính sách bảo mật thông tin được chúng tôi đề cập ngay sau đây nhé.
            </p></i>
            <p class="main_item1">Bất kể trong vai trò là người dùng doanh nghiệp hay cá nhân khi đã thực hiện thao tác đăng ký tài khoản và khai báo các thông tin cá nhân trên hệ thống của PC365 nói riêng và timviec365.com nói chung, đã chính thức chấp nhận những quy định, thỏa thuận về chính sách bảo mật thông tin riêng tư của hệ thống.</p>
            <p>Chúng tôi luôn đảm bảo sự cam kết về trách nhiệm bảo mật thông tin cá nhân liên quan đến người dùng.</p>
            <h2 class="heading">1. PHẠM VI VÀ MỤC ĐÍCH THU THẬP THÔNG TIN DỮ LIỆU</h2>
            <p class="main_item1">PC365 của timviec365.com là đơn vị trung gian đứng ra lưu trữ và sắp xếp một cách có hệ thống các dữ liệu từ doanh nghiệp sử dụng phần mềm chấm công đến nhân viên sử dụng phần mềm. Tất cả những thông tin dữ liệu đó liên quan đến số điện thoại, địa chỉ email, địa chỉ của người dùng, thông tin người dùng (mật khẩu và tên đăng nhập), dữ liệu khuôn mặt, vị trí điểm danh của nhân viên và tọa độ công ty .... Đây cũng chính là thông tin mà hệ thống chỉ dẫn của PC365 buộc các cá nhân, doanh nghiệp, tổ chức phải tiến hành khai báo khi có nhu cầu trở thành thành viên. Bởi vì những thông tin này, đặc biệt là vị trí của người dùng và tọa độ của công ty, bán kính từ công ty đến vị trí mà nhân viên điểm danh này liên quan trực tiếp đến mục đích đảm bảo quá trình ghi nhận công cán chính xác của nhân viên mà không phải phải phụ thuộc vào con người. Cụ thể, là thông qua bán kính từ vị trí người dùng chấm công đến công ty ở một thời điểm nhất định sẽ đảm bảo được là nhân viên có thực sự đến công ty chấm công và vào ca đúng giờ để làm việc hay không. Trong khi đó, những dữ liệu về nhân trắc học như khuôn mặt giúp doanh nghiệp không bỏ lọt những trường hợp chấm công hộ và kiểm soát sát sao hơn tình trạng chấm công, từ đó quản lý về công cán cũng như ý thức nhân viên tốt hơn.</p>
            <p class="main_item1">Nhấn mạnh rằng, tất cả những thông tin do này buộc người dùng báo 100% phục vụ lợi ích của doanh nghiệp sử dụng và tối ưu quá trình chấm công, kiểm soát công cán tốt hơn cho nhân viên, xem lịch, kế hoạch làm việc dễ dàng cho nhân viên mà không hướng đến mục đích cá nhân hay những mục đích xấu. Những thông tin này chính là là cơ sở và căn cứ để chúng tôi có thể chủ động liên hệ với người dùng khi có nhu cầu, nhằm đảm bảo các quyền, lợi ích cá nhân của người dùng khi sử dụng phần mềm.</p>
            <p class="main_item1">Vì vậy, mọi thành viên là các doanh nghiệp đăng ký đến nhân viên trong doanh nghiệp đó khi có mặt trên hệ thống của PC365, đã đăng ký tài khoản với tất cả những thông tin được khai báo cần có trách nhiệm trong việc tự giác và chủ động bảo vệ thông tin dữ liệu cá nhân của mình. Bao gồm các thông tin như mật khẩu đăng nhập, tên đăng nhập, địa chỉ email và số điện thoại,... Bên cạnh đó, đối với những hành vi hoạt động bị liệt kê vào danh mục sử dụng thông tin dữ liệu sai quy định pháp luật, làm dụng, trái phép, trộm cắp thông tin,... cần được toàn bộ thành viên trên PC365 có nghĩa vụ thông báo kịp thời cho hệ thống hoặc đơn vị chủ quản để giải quyết.</p>
            <h2 class="heading">2. PHẠM VI SỬ DỤNG THÔNG TIN</h2>
            <p class="main_item1">Toàn bộ những thông tin do người dùng khai báo trong quá trình đăng ký tài khoản thành viên của website timviec365.com nói chung và PC365 nói riêng được chúng tôi sử dụng trong các mục đích như sau:</p>
            <p class="main_item1 main_item2"> <span class="Dot">&bull;</span>Sử dụng trong việc cung cấp dịch vụ, tính năng mới, hữu ích đến các người sử dụng, nổi bật nhất chính là giúp nhân viên chấm công dễ dàng và các doanh nghiệp quản lý công cán phục vụ tính lương cho nhân viên nhanh chóng hơn.</p>
            <p class="main_item1 main_item2"> <span class="Dot">&bull;</span>Sử dụng trong việc truyền tải các thông tin quan trọng trong quá trình trao đổi giữa PC365 và thành viên bao gồm là các doanh nghiệp sử dụng và hỗ trợ, tư vấn cho nhân viên trong các doanh nghiệp này sử dụng phần mềm dễ dàng. </p>
            <p class="main_item1 main_item2"> <span class="Dot">&bull;</span>Những thông tin này được chúng tôi sử dụng trong việc kịp thời phòng chống, ngăn ngừa những hành vi cố tình ăn cắp, phá hoại tài khoản của người dùng khác. Hoặc hành vi cố tình giả mạo người dùng.</p>
            <p class="main_item1 main_item2"> <span class="Dot">&bull;</span>Sử dụng thông tin trong việc kết nối liên hệ với các thành viên, thực hiện các giải đáp, giải quyết trong những tình huống hay trường hợp đặc biệt.</p>
            <p class="main_item1 main_item2"> <span class="Dot">&bull;</span>PC365 tuyệt đối cam kết không sử dụng các thông tin cá nhân của người dùng trên hệ thống cho những mục đích khác với mục đích ban đầu đã đưa ra. Đó là liên hệ và xác thực những giao dịch có liên quan đến website.</p>
            <p class="main_item1">Đối với những trường hợp cần cung cấp thông tin cá nhân, được yêu cầu bởi các cơ quan, đơn vị chức năng của Pháp luật Việt Nam có thẩm quyền. PC365 có trách nhiệm chủ động và tích cực trong quá trình phối hợp, để đưa những thông tin người dùng khi có yêu cầu cụ thể. Chẳng hạn như được yêu cầu khai báo thông tin từ cơ quan điều tra, Tòa án, Viện kiểm sát,... trong trường hợp có dấu hiệu bất hợp pháp của khách hàng. Ngoài những trường hợp bất khả kháng, không ai có quyền hoặc có thể xâm phạm vào quyền riêng tư cá nhân hay vi phạm bảo mật đối với người dùng trên hệ thống.</p>
            <h2 class="heading">3. THỜI HẠN LƯU TRỮ THÔNG TIN</h2>
            <p class="main_item1">Trong trường hợp cá nhân thành viên có yêu cầu hủy bỏ, hoặc tự cá nhân thành viên trực tiếp thực hiện thao tác hủy bỏ sau khi đăng nhập thành công vào phần mềm thì thông tin mới được xóa. Nếu không, toàn bộ thông tin dữ liệu của cá nhân thành viên vẫn được lưu trữ tại hệ thống. Như vậy, có thể thấy, dữ liệu cá nhân trên timviec365.com không bao giờ bị mất đi, ngoài những trường hợp chủ sở hữu mong muốn thực hiện điều đó.</p>
            <h2 class="heading">4. THÔNG TIN VỀ ĐƠN VỊ LƯU TRỮ, THU THẬP VÀ QUẢN LÝ THÔNG TIN NGƯỜI DÙNG CỦA PC365</h2>
            <p class="main_item1 main_item2"> <span class="Dot">&bull;</span>Công ty chủ quản phần mềm: Công ty TNHH MTV Nguồn Nhân lực 365</p>
            <p class="main_item1 main_item2"> <span class="Dot">&bull;</span>Tên giao dịch quốc tế: 365 HUMAN RESOURCES ONE MEMBER COMPANY LIMITED</p>
            <p class="main_item1 main_item2"> <span class="Dot">&bull;</span>Mã số thuế: 0109218540</p>
            <p class="main_item1 main_item2"> <span class="Dot">&bull;</span>Trụ sở: Số 206 Định Công Hạ , Phường Định Công, Quận Hoàng Mai, Thành phố Hà Nội, Việt Nam</p>
            <p class="main_item1 main_item2"> <span class="Dot">&bull;</span>Số di động: 0971 335.869</p>
            <p class="main_item1 main_item2"> <span class="Dot">&bull;</span>Số máy bàn: 024 36.36.66.99</p>
            <p class="main_item1 main_item2"> <span class="Dot">&bull;</span>Email: Timviec365com@gmail.com</p>
            <h2 class="heading">5. CÔNG CỤ VÀ PHƯƠNG TIỆN ĐỂ NGƯỜI DÙNG CHỦ ĐỘNG CHỈNH SỬA THÔNG TIN CÁ NHÂN</h2>
            <p class="main_item1">- Mọi thành viên trên hệ thống timviec365.com nói riêng và PC365 nói riêng có quyền chủ động trong quá trình kiểm tra, điều chỉnh thông tin hay cập nhật những dữ liệu mới, dữ liệu khác vào tài khoản của mình. Để làm được điều này, người dùng hãy đăng nhập thành công vào tài khoản cá nhân của mình, sau đó thực hiện các thao tác chỉnh sửa trên chính hệ thống. Hoặc có thể liên hệ với bộ phận hỗ trợ của PC365 để được điều chỉnh theo mong muốn một cách nhanh chóng và kịp thời.</p>
            <p class="main_item1">- Trong trường hợp, người dùng phát hiện tài khoản của mình bị một bên thứ ba trộm cắp hoặc bị cá nhân nào đó tiết lộ cho bên thứ ba, cần nhanh chóng báo cáo với Ban quản lý của timviec365.com để được giải quyết. Sau khi tiếp nhận thông tin khai báo, Ban quản lý của hệ thống sẽ thực hiện các kiểm tra, xác thực lại thông tin và có nghĩa vụ giải đáp kết quả xác nhận cho người dùng. Tiến hành hướng dẫn, hỗ trợ người dùng trong quá trình lấy và nhận lại thông tin như ban đầu.</p>
            <p class="main_item1">Thắc mắc của quý khách hàng nên được báo cáo hoặc gửi về thông tin liên hệ của công ty chủ quản của PC365 - timviec365.com:</p>
            <p class="main_item1 main_item2"> <span class="Dot">&bull;</span>Số di động: 0971 335.869</p>
            <p class="main_item1 main_item2"> <span class="Dot">&bull;</span>Số máy bàn: 024 36.36.66.99</p>
            <p class="main_item1 main_item2"> <span class="Dot">&bull;</span>Email: Timviec365com@gmail.com</p>
            <h2 class="heading">6. CAM KẾT CỤ THỂ CỦA PC365 VỀ BẢO MẬT DỮ LIỆU CHO NGƯỜI DÙNG</h2>
            <p class="main_item1">- Toàn bộ những thông liên quan đến dữ liệu cá nhân của người dùng (là thành viên trên hệ thống) sẽ được timviec365.com đảm bảo về vấn đề bảo vệ, bảo mật dữ liệu. Timviec365.com nói chung, PC365 nói chung chỉ được phép sử dụng các thông tin dữ liệu cá nhân của người dùng trong các trường hợp đã được người dùng đồng ý và thỏa thuận cho phép. Ngoài ra, trừ những trường hợp bất khả kháng như yêu cầu của các đơn vị, cơ quan chức năng của Nhà nước có thẩm quyền.</p>
            <p class="main_item1">- Timviec365.com nói chung và phần mềm PC365 cam kết  rằng không cung cấp, không tiết lộ, không chuyển giao cho một đơn vị thứ ba nào bên ngoài và cũng không sử dụng các thông tin dữ liệu cá nhân vào các mục đích ngoài xác nhận và liên hệ. Ngoài trừ đã được sự đồng ý và cho phép của người dùng trên hệ thống.</p>
            <p class="main_item1">- Đặc biệt, trong trường hợp nếu như máy chủ hệ thống của PC365 - timviec365.com bị một bên thứ ba cố tình xâm nhập, tấn công, trộm cắp làm mất thông tin dữ liệu cá nhân của người dùng, thì chúng tôi - đơn vị chủ quản sẽ có trách nhiệm trong vấn đề thông báo sự việc, vấn đề không may xảy ra cho cơ quan, đơn vị chức năng có thẩm quyền để giải quyết. Tất cả tiến trình giải quyết và kết quả giải quyết sẽ được PC 365 - timviec365.com chủ động thông báo đến người dùng.</p>
            <p class="main_item1">- Trong trường hợp toàn bộ thông tin mà người dùng là thành viên khai báo, cung cấp ban đầu không chính xác, không hợp pháp, thì Ban quản lý của hệ thống timviec365.com sẽ không có trách nhiệm phải giải quyết hoặc lấy lại thông tin dữ liệu cá nhân của người dùng trong trường hợp thông tin bị mất cắp.</p>
            <p class="main_item1">Trên đây là những nội dung quan trọng trong Chính sách bảo mật thông tin của timviec365.vn nói chung và PC365 nói riêng. Hãy tìm hiểu và đọc kỹ những quy định cụ thể này trước khi tham gia vào các giao dịch và trải nghiệm dịch vụ của timviec365.com, cụ thể là trên phần mềm PC365 bạn nhé!</p>
        </div>
    </div>
</div>